{
 "title": "Raspberry Pi nginx Access Logs",
 "tags": [
  "infrastructure",
  "logs",
  "loki",
  "nginx",
  "raspberry"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "nginx,traefik,all" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({job=\"nginx-access\"}, host)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values({job=\"nginx-access\", host=~\"$host\"}, method)"
   },
   {
    "name": "exclude_monitoring_request_regex",
    "query": ".*(/api/ds/query|/api/login/ping|/api/live/ws|/api/annotations|/api/plugins|/api/prometheus/|/api/datasources/uid/.*/resources/label/|/apis/|dashboardUID=raspberry-nginx-access|/loki/api/v1/|/ready|/metrics).*"
   },
   {
    "name": "exclude_monitoring_router_regex",
    "query": ".*(tlanexli|grafana|prometheus|loki|alloy|monitor).*"
   },
   {
    "name": "exclude_monitoring_line_regex",
    "query": ".*(tlanexli|/api/ds/query|/api/login/ping|/api/live/ws|/api/annotations|/api/plugins|/api/prometheus/|/api/datasources/uid/.*/resources/label/|/apis/|dashboardUID=raspberry-nginx-access|/loki/api/v1/|/ready|/metrics|grafana|prometheus|loki|alloy).*"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\" [$__range])) or vector(0)) + (sum(count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\", status=~\"4..\"} !~ \"${exclude_monitoring_line_regex}\" [$__range])) or vector(0)) + (sum(count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | status =~ \"4..\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\", status=~\"5..\"} !~ \"${exclude_monitoring_line_regex}\" [$__range])) or vector(0)) + (sum(count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | status =~ \"5..\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "Unique Client IPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((sum by (remote_addr) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\" | pattern \"<remote_addr> - <remote_user> [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\"<_>\" [$__range]))) or (sum by (remote_addr) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range]))))"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host) (rate({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} [$__interval]))",
     "legendFormat": "nginx {{host}}"
    },
    {
     "expr": "sum by (router) (rate({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__interval]))",
     "legendFormat": "traefik {{router}}"
    }
   ]
  },
  {
   "title": "4xx per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host) (rate({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\", status=~\"4..\"} [$__interval]))",
     "legendFormat": "nginx {{host}}"
    },
    {
     "expr": "sum by (router) (rate({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | status =~ \"4..\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__interval]))",
     "legendFormat": "traefik {{router}}"
    }
   ]
  },
  {
   "title": "5xx per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host) (rate({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\", status=~\"5..\"} [$__interval]))",
     "legendFormat": "nginx {{host}}"
    },
    {
     "expr": "sum by (router) (rate({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | status =~ \"5..\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__interval]))",
     "legendFormat": "traefik {{router}}"
    }
   ]
  },
  {
   "title": "Top Request Paths (nginx + Traefik)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "topk(10, (sum by (request) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\" | pattern \"<remote_addr> - <remote_user> [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\"<_>\" [$__range]))) or (sum by (request) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | parsed_method=~\"${method:regex}\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range]))))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Top Client IPs (nginx + Traefik)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "topk(10, (sum by (remote_addr) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\" | pattern \"<remote_addr> - <remote_user> [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\"<_>\" [$__range]))) or (sum by (remote_addr) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | parsed_method=~\"${method:regex}\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range]))))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top Cloudflare Client IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_cf_connecting_ip) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} | pattern \"<remote_addr> - <remote_user> [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" \\\"<host_header>\\\" \\\"<server_name>\\\" \\\"<scheme>\\\" \\\"<request_uri>\\\" \\\"<request_time>\\\" \\\"<upstream_addr>\\\" \\\"<upstream_status>\\\" \\\"<upstream_response_time>\\\" \\\"<http_x_forwarded_for>\\\" \\\"<http_cf_connecting_ip>\\\" \\\"<http_cf_ray>\\\"\" [$__range])))",
     "legendFormat": "{{http_cf_connecting_ip}}"
    }
   ]
  },
  {
   "title": "Top User Agents (nginx + Traefik)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(10, (sum by (http_user_agent) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\" | pattern \"<remote_addr> - <remote_user> [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\"<_>\" [$__range]))) or (sum by (http_user_agent) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | parsed_method=~\"${method:regex}\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range]))))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Suspicious Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\" | pattern \"<remote_addr> - <remote_user> [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\"<_>\" | request =~ \".*(wp-login|xmlrpc|phpunit|[.]env|[.]git|/admin|/login|/register|/setup|/sitemap|/vendor/|/[.]well-known/pki-validation|/wp-admin|/wordpress|/administrator|/user/login|/dashboard|/account|/payment|/order|/subscribe|/shop|/plans|/signup).*\" [$__range])) or vector(0)) + (sum(count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request =~ \".*(wp-login|xmlrpc|phpunit|[.]env|[.]git|/admin|/login|/register|/setup|/sitemap|/vendor/|/[.]well-known/pki-validation|/wp-admin|/wordpress|/administrator|/user/login|/dashboard|/account|/payment|/order|/subscribe|/shop|/plans|/signup).*\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "Top Suspicious Client IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "topk(15, (sum by (remote_addr) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\" | pattern \"<remote_addr> - <remote_user> [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\"<_>\" | request =~ \".*(wp-login|xmlrpc|phpunit|[.]env|[.]git|/admin|/login|/register|/setup|/sitemap|/vendor/|/[.]well-known/pki-validation|/wp-admin|/wordpress|/administrator|/user/login|/dashboard|/account|/payment|/order|/subscribe|/shop|/plans|/signup).*\" [$__range]))) or (sum by (remote_addr) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request =~ \".*(wp-login|xmlrpc|phpunit|[.]env|[.]git|/admin|/login|/register|/setup|/sitemap|/vendor/|/[.]well-known/pki-validation|/wp-admin|/wordpress|/administrator|/user/login|/dashboard|/account|/payment|/order|/subscribe|/shop|/plans|/signup).*\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range]))))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Suspicious Paths",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "topk(15, (sum by (request) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\" | pattern \"<remote_addr> - <remote_user> [<time_local>] \\\"<parsed_method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\"<_>\" | request =~ \".*(wp-login|xmlrpc|phpunit|[.]env|[.]git|/admin|/login|/register|/setup|/sitemap|/vendor/|/[.]well-known/pki-validation|/wp-admin|/wordpress|/administrator|/user/login|/dashboard|/account|/payment|/order|/subscribe|/shop|/plans|/signup).*\" [$__range]))) or (sum by (request) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request =~ \".*(wp-login|xmlrpc|phpunit|[.]env|[.]git|/admin|/login|/register|/setup|/sitemap|/vendor/|/[.]well-known/pki-validation|/wp-admin|/wordpress|/administrator|/user/login|/dashboard|/account|/payment|/order|/subscribe|/shop|/plans|/signup).*\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range]))))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Traffic by Country",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum by (http_cf_ipcountry) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\", http_cf_ipcountry=~\"[A-Z]{2}\"}[$__range])))",
     "legendFormat": "{{http_cf_ipcountry}}"
    }
   ]
  },
  {
   "title": "Traffic Origin Map",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (http_cf_ipcountry) (count_over_time({job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\", http_cf_ipcountry=~\"[A-Z]{2}\"}[$__range]))",
     "legendFormat": "{{http_cf_ipcountry}}"
    }
   ]
  },
  {
   "title": "Top Traefik Routers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "topk(10, sum by (router) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range])))",
     "legendFormat": "{{router}}"
    }
   ]
  },
  {
   "title": "Top Traefik Paths",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "topk(10, sum by (request) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range])))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Top Traefik Status Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sort_desc(sum by (status) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top Traefik Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 65 },
   "targets": [
    {
     "expr": "topk(10, sum by (service_url) (count_over_time({namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\" [$__range])))",
     "legendFormat": "{{service_url}}"
    }
   ]
  },
  {
   "title": "Combined Live Log Stream",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "{job=\"nginx-access\", host=~\"${host:regex}\", method=~\"${method:regex}\"} !~ \"${exclude_monitoring_line_regex}\""
    },
    {
     "expr": "{namespace=\"traefik-v2\", container=\"traefik\"} |~ \"stdout F [0-9.:]+ - - \\\\[\" | pattern \"<_> stdout F <remote_addr> - - [<time_local>] \\\"<method> <request> <protocol>\\\" <status> <body_bytes_sent> \\\"<http_referer>\\\" \\\"<http_user_agent>\\\" <request_count> \\\"<router>\\\" \\\"<service_url>\\\" <request_duration>\" | request !~ \"${exclude_monitoring_request_regex}\" | router !~ \"${exclude_monitoring_router_regex}\""
    }
   ]
  }
 ]
}